# NumPy Notes

Covers arrays and indexing & selection

**Import NumPy**

In [1]:
import numpy as np

 ## 1. Arrays


**1.1 Same value arrays**

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
# creating vector with '5's
np.ones(5)*5

# np.zeros(5)+5 works as well

array([5., 5., 5., 5., 5.])

**1.2 Ranged Arrays**

In [5]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
# with steps
np.arange(0,9,2)

array([0, 2, 4, 6, 8])

**1.3 Reshaping**

In [7]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**1.4 Identity Matrix**

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**1.5 Random Array**

In [9]:
np.random.randn(9).reshape(3,3)

array([[-0.1148921 , -0.39884863, -1.09094553],
       [-0.73114431, -0.76821724,  1.13264845],
       [-2.04760556, -0.46313962,  0.54272343]])

**1.6 Linearly Spaced Points**

In [10]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

 ## 2. Indexing & Selection


In [11]:
matrix = np.arange(1,17).reshape(4,4)
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

**2.1 Grab Row**

In [12]:
matrix[0:1,:]

array([[1, 2, 3, 4]])

In [13]:
matrix[2:3]

array([[ 9, 10, 11, 12]])

**2.2 Grab Column**

In [14]:
matrix[:,0:1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [15]:
matrix[:,3:4]

array([[ 4],
       [ 8],
       [12],
       [16]])

**2.3 Grab multiple points**

In [16]:
matrix[2:,2:]

array([[11, 12],
       [15, 16]])

In [17]:
matrix[1:2,1:]

array([[6, 7, 8]])

In [18]:
matrix[:3,2:3]

array([[ 3],
       [ 7],
       [11]])

**2.3 Grab singular point**

In [19]:
matrix[3,3]

16